
== Introduction

=== Purpose

The purpose of this document is to establish an understanding between
{collaboration-party} and CalConnect on cooperation on standards development.

This document formalizes the process of collaboration of {collaboration-party}
and CalConnect to cooperate and to
enable the collaborative development of standards.

The resulting standards are to be jointly published by {collaboration-party} and CalConnect
as "ISO/CalConnect Standards", according to processes described in this document.


=== Background

One of the objectives of ISO is to facilitate the international
exchange of goods and services through the development of International
Standards.

The ISO Council has adopted a policy of inclusiveness
and encourages cooperation between ISO and other standardizing bodies,
where such cooperation would serve to ensure effective and efficient
use of resources available for standardization activities.

CalConnect aims to facilitate interoperability of collaborative
technologies with open standards, in particular on calendar, scheduling,
and contacts; its standards are globally recognized and widely applied.


=== Intention

ISO and CalConnect agree to the principles of cooperation described in this document,
in all fields subject to approval by the ISO Technical Management Board and the
CalConnect TC PUBLISH and TCC.


=== Process cooperation

ISO and CalConnect wish to avoid duplication of efforts by their
respective committees.

ISO produces International Standards in accordance with processes described in
<<ISODIR1C>> and <<ISODIR1>>, with the standard documents drafted
in accordance with the editorial rules of <<ISODIR2>>.

CalConnect creates publicly available CalConnect Standards through
a consensus-based standardization process described in
<<CALSTD>>, and standard documents created in accordance with <<CALDOC>>.

////
CalConnect is a Category A Liaison organization
with {collaboration-party}, and is allowed to submit standardization documents
through the ISO "`Fast-Track`" and PAS submission procedures
(in accordance with <<ISODIR1>> and <<ISODIR1C>>).

However, both {collaboration-party} and CalConnect believe that
a collaborative development process provides additional benefits:
////

Both {collaboration-party} and CalConnect believe that
cooperation at the standards development process level
provides the following benefits:

* maximizes the deliverable expertise of their experts; and
* maximizes the quality of the resulting International Standard.

This agreement facilitates a collaborative development process
for the creation of joint publications (ISO/CalConnect Standards)
between ISO and CalConnect.
