
[[ipr]]
== Intellectual property rights

=== Free of restrictions

// From OGC
Both parties agree that text of all working documents developed under this agreement, as well as the final ISO deliverables will remain free of IPR restrictions that would limit their application.

=== Copyright

Copyright of standardization deliverables created under this document
will be jointly owned by both parties.


=== CalConnect-sourced documents

// From OGC
CalConnect grants ISO a world-wide, non-exclusive, non-sub-licensable
license (except for national body adoption),
to use contents of CalConnect submitted documents to ISO,
for the development and publishing of the deliverables under this agreement.

{collaboration-party} agrees that the resulting ISO deliverable will
contain a suitable statement similar to the one in the
base documents indicating that the standard was derived from the
relevant CalConnect sourced documents.

=== Patented content

Patented content in a standard will be governed by the ISO directives and the CalConnect IPR policy. Any patents involved knowingly in the document must be made transparent prior to the DIS stage.

=== Re-publishing

This agreement binds the parties that the re-publishing of content
developed under this agreement will adhere to this agreement.

ISO and CalConnect individually retain the rights to publish all
documents developed under this agreement according to their own
practices.

Publishing arrangements between ISO and ISO member countries are
unchanged by this agreement.
