
[[process]]
== Collaborative development process

=== General

A collaborative development process is crucial to effective development
of work items between {collaboration-party} and CalConnect. Both organizations
agree to align appropriate internal processes and procedures
in order to facilitate joint development of work items.

Experts in {collaboration-party} are encouraged to participate in the technical
work on CalConnect technologies by participating in CalConnect
technical committees.

////
Since the desire of both organizations is that technical changes are
not made once work has been passed to {collaboration-party} as a Draft
International Standard (DIS), {collaboration-party} national bodies will encourage
their technical experts to participate in OGC working groups.
////


=== Alignment of project stages

The following table provides a mapping between ISO project stages and
CalConnect project stages. This document identifies stages
according to the ISO project stage names.

[cols="1,1,1",options="header"]
.Alignment between ISO and CalConnect project stages
|===
|Identification in this document
|ISO harmonized stage (<<ISODIR1>>)
|CalConnect stage

|*Preliminary*
|00 Preliminary
|00 Preliminary

|*Proposal*
|10 Proposal
|10 Proposal

|*Preparatory*
|20 Preparatory
|20 Preparatory

|*Committee*
|30 Committee
|30 Committee

|*Enquiry*
|40 Enquiry
|40 Enquiry

|*Approval*
|50 Approval
|50 Approval

|*Publication*
|60 Publication
|60 Publication

|*Review*
|90 Review
|90 Review

|*Withdrawal*
|95 Withdrawal
|95 Withdrawal

|===


=== Track synchronization

ISO deliverables can be developed according to different tracks
and timelines detailed in <<ISODIR1>> and <<ISODIR1C>>.

For a project under this agreement, CalConnect agrees to adopt
a developmental track not slower than
the track selected in {collaboration-party} to ensure the synchronicity between
development outcome and publication.


=== First draft

A first draft of the standardization deliverable may be created
for proposal submission, or may be created in the Committee stage.
The draft shall be created through a collaboration process between
experts from both organizations, or at least, the proposing
organization should have received input from the other organization.

CalConnect agrees that any draft submitted to {collaboration-party}
shall adhere to the requirements detailed in <<ISODIR2>> and
applicable {collaboration-party} internal guidelines.


=== Preliminary stage

At the first instance where either party wishes to co-develop
a project with the other party, it should be raised to the JCG.
The JCG shall consult the stakeholders to determine appropriateness
of the project and advise the proposer.

If the project is rejected by the JCG, its output may still be
developed within CalConnect if it is appropriate, and its output may
still be proposed to the JCG for co-development in later stages.


=== Proposal stage

When the JCG determines interest within {collaboration-party} to co-develop the
proposed project, CalConnect should submit an NWIP to {collaboration-party}
for ballot indicating its wish to co-develop the proposed project.

If accepted, the project shall be adopted on both sides by a CalConnect
TC and an appropriate workgroup in {collaboration-party}.
Members of the project group
shall be represented by experts in both parties in accordance with
the rules of the liaison relationship.
This project shall then be
listed in the JCG register of co-developed projects.

If rejected, its output may still be developed within CalConnect if it
is appropriate, and its output may still be proposed to the JCG for
co-development in later stages.


// Once the document is accepted in TC 211 via ballot, a project
// leader shall be selected from the project group.


////
As a general guidance, whenever sufficient interest in a specific topic
is sufficient enough to warrant a working group in OGC, a new work item
proposal (NP) with similar scope will be generated. Conversely,
whenever a NP is accepted by {collaboration-party}, a working group will be formed
in OGC to develop corresponding interface technology and bring software
implementations to the marketplace. Similarly, Industry Implementation
Specifications Version 0.0 that are accepted by OGC in response to a
Request For Proposal (RFP) may be submitted to {collaboration-party} as a
Committee Draft (CD). When these Specifications reach version V1.0,
they may be submitted to {collaboration-party} for consideration as a Draft
International Standard (DIS). An OGC version V2.0 is a document that
has been widely accepted as stable. V2.0 is the equivalent of a Final
Draft International Standard (FDIS). In the following chart the
abbreviation IS relates to an International Standard.
////



=== Preparatory, Committee, Enquiry stages

The goal of these stages are to create an approved, balloted
draft of the deliverable by {collaboration-party}.

In these stages the members of the project groups within both
organizations shall collaborate closely to ensure efficient
and effective development of the deliverable of
the respective stages. The deliverable shall be developed
jointly by experts of both organizations.

The approval process at {collaboration-party} shall be adhered to.
CalConnect agrees to synchronize its project stage with
the corresponding {collaboration-party} stage.

Specifically:

* If a deliverable is approved by ballot at {collaboration-party},
  CalConnect will advance the project stage at its
  project group accordingly.
* If a deliverable is rejected by ballot at {collaboration-party},
  CalConnect will not advance project stage at its
  project group, unless a re-ballot at {collaboration-party} approves
  advancement of the deliverable.
* In cases where a development stage is optional and skipped
  in accordance with <<ISODIR1>> and <<ISODIR1C>>, CalConnect
  shall set the stage of its project at the corresponding
  stage.


=== Public review

A public review period of 60 days is required for the compliance
to <<WTOTBT>> rules, for which both ISO and CalConnect adhere to.

A 60-day public review shall be held in the DIS stage of the ISO deliverable.

Comments to {collaboration-party} shall be performed according to <<ISODIR1>> and <<ISODIR1C>>;
comments to CalConnect shall be performed through CalConnect's public review procedure.

The parties agree to synchronize the dates of review periods for the
maximum benefit to the joint work item.


////
Public draft period will be an open one at CalConnect, it will be at
the stage of pre-publication.
////

=== Abandonment

A joint work item may be abandoned by one of the two parties if it sees
it being inappropriate or is no longer interested or able to contribute
to the joint work item. Each party is allowed to abandon the joint
work, which at that point will become sole work of the other party.

A notice of such must be sent by the abandoning party to the JCG and
distributed by both parties to its members.

The abandoning party, if the abandoned work is carried on by the other
party, is required to explicitly agree that the copyright of such work
is to be waived to the other party to allow publication of the document.

If the abandons party wishes to rejoin an abandoned work item, it is
agreed in this agreement that it is allowed, given a notice is filed at
the JCG, unless in exceptional circumstances.


=== Additional collaborators

Parties may bring in additional collaborators under this agreement,
given it is approved by the JCG, that the provisions of this agreement
are fully satisfied by agreements present between all collaborators.

=== Notification

Notification of availability of new documents within CalConnect
will be announced to the appropriate {collaboration-party} working groups
and CalConnect technical committees.

=== Availability of working documents

Drafts and working documents are available according to
each party's normal practices.

=== Distribution of publication

After an ISO ballot on the acceptance of a joint work item as
DIS, FDIS or IS, the joint work item will be published
as a CalConnect Standard.


=== Promotional activities

Promotional programs will be shared between {collaboration-party}
and CalConnect for the purpose of coordinating marketing activities
via the JCG.
